V15 (#95)
* Remove rice (#61)

* Remove rice from German translation

* Remove rice from Bulgarian translation

* Remove rice from values-el/strings.xml

* Remove rice from values-es/strings.xml

* Remove rice from values-fr/strings.xml

* Remove rice

Remove all types of rice due to a high level of arsenic (see https://nutritionfacts.org/?fwp_search=arsenic%20rice&fwp_content_type=video).

* Add and Update Chinese Translation

* Russian translation (#66)

* create values-ru/strings.xml

just an Eng. copy so far

* Start translating strings.xml

* continue with russian translation

* Update strings.xml

* continue with russian translation

* finish beans

* translate till mushrooms

* start spices

* finish spices

* start exercises

* continue exercies

* translate till cups

* finish before check

* finish russian translation

This first version of a Russian translation is deemed finished after a couple of grammar checks and XML validation.

* Removed some duplicated strings

* Add romanian translations

* Rename "Nuts" to "Nuts and Seeds"


Fix issue #73

* Fix issue #82 (#83)

Error: Non-translatable resources should only be defined in the base values/ folder

* Fix incorrect dialog title for Generate Full Data button (#80)

* Rename "Spices" to "Herbs and Spices" (#86)

Fix issue #74

* Add romanian translations (#79)

* Using the latest gradle and build tools

* Add support for deploying to F-Droid repository (#81)

* Use Get it on Google Play icon (#92)

* Add more cruciferous vegetables; see #64

* build.gradle updates

* Updated README.md with v15 info

* Minor changes

* Fixed many warnings Android Studio found in the various strings.xml files

* Moved Kohlrabi so the English translation is in sorted order

* Updated fabric and crashlytics versions

* Reverted back to the single FoodInfo.init() method because the previous two step process was causing crashes.

* Add output.json to .gitignore

* versionCode 41